# AI in Business – Midterm (Student)

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score,roc_auc_score

## Load dataset and perform EDA

In [6]:
df=pd.read_csv('retail_ai_midterm_dataset.csv')
df.head()

,customer_id,age,annual_income,spending_score,purchase_frequency,avg_transaction_value,membership_years,website_visits_month,returns_rate,churn
0,1,65,148317,80,18,486,8,46,0.25,0
1,2,22,110847,66,16,49,9,24,0.45,0
2,3,43,146771,8,32,66,6,15,0.16,0
3,4,72,79324,98,36,394,2,38,0.43,0
4,5,21,60594,30,52,650,7,22,0.15,0

In [11]:
df.shape

(800, 10)

In [8]:
df.describe(include='all')

,customer_id,age,annual_income,spending_score,purchase_frequency,avg_transaction_value,membership_years,website_visits_month,returns_rate,churn
count,800.0000,800.000000,800.00000,800.000000,800.000000,800.000000,800.00000,800.000000,800.000000,800.000000
mean,400.5000,46.570000,89068.26000,50.242500,29.497500,334.473750,5.41625,25.237500,0.250837,0.217500
std,231.0844,16.575993,36545.86473,28.433286,17.371592,197.835925,3.43296,14.511351,0.146942,0.412804
min,1.0000,18.000000,25088.00000,1.000000,1.000000,5.000000,0.00000,0.000000,0.000000,0.000000
25%,200.7500,32.000000,58244.25000,26.000000,14.000000,171.000000,2.00000,12.000000,0.120000,0.000000
50%,400.5000,47.000000,89941.00000,51.000000,29.000000,326.500000,5.00000,26.000000,0.245000,0.000000
75%,600.2500,61.000000,121553.25000,74.000000,45.000000,496.250000,8.00000,38.000000,0.380000,0.000000
max,800.0000,74.000000,149958.00000,99.000000,59.000000,697.000000,11.00000,49.000000,0.500000,1.000000

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customer_id            800 non-null    int64
 1   age                    800 non-null    int64
 2   annual_income          800 non-null    int64
 3   spending_score         800 non-null    int64
 4   purchase_frequency     800 non-null    int64
 5   avg_transaction_value  800 non-null    int64
 6   membership_years       800 non-null    int64
 7   website_visits_month   800 non-null    int64
 8   returns_rate           800 non-null    float64
 9   churn                  800 non-null    int64
dtypes: float64(1), int64(9)
memory usage: 62.6 KB

In [9]:
df.isnull().sum()

customer_id              0
age                      0
annual_income            0
spending_score           0
purchase_frequency       0
avg_transaction_value    0
membership_years         0
website_visits_month     0
returns_rate             0
churn                    0
dtype: int64

# Perform EDA

In [10]:
df["churn"].value_counts()

churn
0    626
1    174
Name: count, dtype: int64

## Train Logistic Regression and Random Forest models

## Perform KMeans clustering and PCA visualization